repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-aws-credentials
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-toml
      - id: pretty-format-json
        args:
          - --autofix
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-exiting-file=true
          - --hook-config=--create-file-if-not-exist=true
        # exclude: (\.terraform.*|^environment/.*|^github/repo/.*|vault/.*|boundary/.*)$
      # - id: terraform_tflint
      #   args:
      #     - '--args=--only=terraform_deprecated_interpolation'
      #     - '--args=--only=terraform_deprecated_index'
      #     - '--args=--only=terraform_unused_declarations'
      #     - '--args=--only=terraform_comment_syntax'
      #     - '--args=--only=terraform_documented_outputs'
      #     - '--args=--only=terraform_documented_variables'
      #     - '--args=--only=terraform_typed_variables'
      #     - '--args=--only=terraform_module_pinned_source'
      #     - '--args=--only=terraform_naming_convention'
      #     - '--args=--only=terraform_required_version'
      #     - '--args=--only=terraform_required_providers'
      #     - '--args=--only=terraform_standard_module_structure'
      #     - '--args=--only=terraform_workspace_remote'
