repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: detect-aws-credentials
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-toml
      - id: pretty-format-json
        args:
          - --autofix
  - repo: local
    hooks:
      - id: terraform-fmt
        name: terraform-fmt
        entry: scripts/terraform_fmt.sh modules
        language: script
        pass_filenames: false
      - id: terraform-docs
        name: terraform-docs
        entry: scripts/terraform_docs.sh modules
        language: script
        pass_filenames: false
      - id: terraform-tflint
        name: terraform-tflint
        entry: scripts/terraform_tflint.sh modules
        language: script
        pass_filenames: false
