name: Terraform Tools Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  tools:
    name: Terraform Tools Execution
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:

    - name: Check out code
      uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Post Format
      if: always() && github.ref != 'refs/heads/main' && (steps.fmt.outcome == 'success' || steps.fmt.outcome == 'failure')
      uses: GetTerminus/terraform-pr-commenter@v2
      with:
        commenter_type: fmt
        commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
        commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}
